### ISSUE TITLE
/images/arrowuppWhite.png is missing

### ISSUE THREAD

**Issue by nick-wallingford** [AVtory/AVtoryWebsite#3]
The footer navbar refers to an arrowuppWhite.png, which is on the /mettavy/ site but not in the github.

**Comment by jasonsneddon** [comment]
[Google](https://www.google.com/search?q=white+arrow+up+icon+png&oq=white+arro&aqs=chrome.0.69i59j69i60j0j69i57j0l2.2216j0j7&sourceid=chrome&ie=UTF-8)

**Comment by d3nise** [comment]
resolved meow =^.,.^= sorry just getting to this...
